name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build frontend only
        run: npx vite build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
<<<<<<< HEAD
=======
          VITE_FIREBASE_AUTH_DOMAIN: "tharagrowth-mvp.web.app"
>>>>>>> 31ddb3b (Configure Firebase for deployment and add a test HTML file)
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
<<<<<<< HEAD
          
=======
        
>>>>>>> 31ddb3b (Configure Firebase for deployment and add a test HTML file)
      - name: Deploy to Firebase Hosting
        run: npx firebase-tools deploy --only hosting --project tharagrowth-mvp
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Output Firebase Hosting URL
        run: echo "🚀 Deployment successful! Your app is available at https://tharagrowth-mvp.web.app"
